language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge
      cache:
        directories: "$HOME/.composer/cache"
      before_install:
        - wget https://phar.phpunit.de/phpunit-4.5.1.phar
      script:
        - php phpunit-4.5.1.phar --verbose $PHPUNIT_FLAGS

sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - |
    PHPUNIT_FLAGS=""

script:
  - phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |

